### ISSUE TITLE
Implicit String Conversion to Int in Mode

### ISSUE THREAD

**Issue by Dae314** [Nordstrom/fileutils-cookbook#10]
I was running into the following problem attempting to change the mode of a file:
```
TypeError
---------
no implicit conversion of String into Integer

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/fileutils/libraries/change_help.rb:86:in `chmod'
/tmp/kitchen/cache/cookbooks/fileutils/libraries/change_help.rb:86:in `file_update'
/tmp/kitchen/cache/cookbooks/fileutils/libraries/change_help.rb:74:in `update'
/tmp/kitchen/cache/cookbooks/fileutils/libraries/change_help.rb:61:in `find_and_update_files'
/tmp/kitchen/cache/cookbooks/fileutils/libraries/change_help.rb:46:in `update_files'
/tmp/kitchen/cache/cookbooks/fileutils/resources/default.rb:40:in `block in class_from_file'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/my_cookbook/recipes/my_recipe.rb

136: fileutils '/var/my_file' do
137:   owner 'root'
138:   group 'system'
139:   file_mode ['0600']
140:   recursive false
141: end
142:

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cache/cookbooks/my_cookbook/recipes/my_recipe.rb:136:in `from_file'

fileutils("/var/my_file") do
  action [:create]
  default_guard_interpreter :default
  declared_type :fileutils
  cookbook_name "my_cookbook"
  recipe_name "my_recipe"
  owner "root"
  group "system"
  file_mode ["0600"]
  recursive false
end

System Info:
------------
chef_version=15.1.36
platform=aix
platform_version=7.2
ruby=ruby 2.6.3p62 (2019-04-16 revision 67580) [powerpc-aix6.1.0.0]
program_name=/opt/chef/bin/chef-client
executable=/opt/chef/bin/chef-client
```

I crafted the resource call based on this code in the README.md:
```
# Change only the top level directory and it's files
# should not change .../stuff/**
fileutils '/export/home/my' do
  recursive false
  files_only true
  file_mode ['0700']
end
```

The problem appears to be in `libraries/change_help.rb` line 86: `f.chmod(mode)`

Based on the problem statement, I was able to fix it by changing my resource call like this:
```
fileutils '/var/my_file' do
  owner 'root'
  group 'system'
  file_mode [0600]
  recursive false
end
```

Note, no '' around the file mode if it is just numbers.

Can you please change the interpretation of these strings/ints so that the behavior is consistent with one of:

1. All hex modes should be specified as strings (e.g. `['0755']`)
2. All hex modes should be specified as integers (e.g. `[0755]`)
3. Both 2 and 3 are valid and interpreted correctly

And please update the README.md to reflect this.

The same problem exists in directory_mode, but I noticed that you're doing some option validation for that attribute.  This actually makes it so you cannot use `[0755]` (validation error) or `['0755']` (type conversion error).  The only way I got around it was to use an integer `0755` without the array.  Using `'0755'` in directory_mode gave me a type conversion error again.

As far as I've tested, working around with `[0755]` for file mode and `0755` for directory_mode works as intended.

**Comment by MarkGibbons** [comment]
Thanks, I'll look at that

**Comment by MarkGibbons** [comment]
Merged, should be fixed.
