### ISSUE TITLE
Not idempotent?

### ISSUE THREAD

**Issue by jvogt** [Nordstrom/fileutils-cookbook#3]
chef-client version: 13.3.42
os: centos/7
the following simple recipe always results in 1 resource updated:

```
test_dir = '/tmp/test_dir'

directory test_dir do
  action :create
end

fileutils test_dir do
  group 'nobody'
end
```

**Comment by MarkGibbons** [comment]
Thank you for catching that.  I'll have a fix shortly.

**Comment by MarkGibbons** [comment]
Version 1.1.6 was release on supermarket.chef.io.

Thanks again.
