### ISSUE TITLE
quick question 

### ISSUE THREAD

**Issue by Dennispetrillo** [Nordstrom/fileutils-cookbook#6]
Hi Mark

Newbie to chef and a question on your cookbook.  I keep getting an error when running:

               could not find recipe default for cookbook fileutils

I'm including your cookbook as:  include_recipe "fileutils::default"

I believe I have the naming correct but can you confirm please?

thanks!

**Comment by MarkGibbons** [comment]
@Dennispetrillo,

This cookbook is a little different.  It has no recipes.  It provides resources you can use in your own cookbooks.  You let your cookbook know about it by adding the fileutils cookbook to the metadata.rb file in your cookbook  with depends 'fileutils' statement.  Then code a fileutils resource to do what you want.

Update if you need more help.

Mark

**Comment by Dennispetrillo** [comment]
Thanks for the quick response!  It worked like a charm!  

Thanks!
